### PR TITLE
Improve create json body

### PR DESCRIPTION
**Pull request by alpaziz**
Created 2 helper functions in utils.r. One to Map Metadata columns from excel to machine_names, and another to map machine_name to/from pretty_name.

reference to #65

### CODE REVIEW

**Comment by alpaziz** [comment]
Understood @seladore . Thanks!

**Comment by alpaziz** [comment]
Hey @seladore ,

I just started referencing the ui_names_lookup. If you think everything is okay, could you please merge?

**Comment by seladore** [comment]
hi @alpaziz, did you confirm that the ui_names_lookup is up to date with the latest version of the form? We briefly talked about it during the team meeting but lmk if you have any questions

**Comment by seladore** [comment]
hi @alpaziz, here is some feedback for the pull request:
__both__
* just a general question, are these functions going to be used by end users? If so, I think they should be exported and documented.

__map_metadata_excel__
- could you add `return()` to the object you're returning?

__map_machine_pretty__
- double check with Tony about using get_fields(), I remember there being an issue with it a while back but it's probably fixed now
- could you look into the following warning 
```Column `machine_name` joining factor and character vector, coercing into character vector ```
- when I ran the code block below, the return value was in machine names, is this the expected output?
```
ddhconnect:::map_machine_pretty(c("field_wbddh_dsttl_upi", "body", "title"), 
from = "machine",
to = "pretty")
```

**Comment by alpaziz** [comment]
Hey @seladore ,

Thanks for the input, I removed the map_pretty, and created a separate script for map_meta_excel. Cleaned the code, and I didn't remove the following code:
`machine_names[]     <- lapply(machine_names, as.character)
  updated_data        <- c(machine_names[, "Value"])
  names(updated_data) <- c(machine_names[, "machine_names"])
  updated_data        <- c(updated_data, c("workflow_status" = "published"))`

as after I removed it a unit test for create_json_body was failing. Please let me know if you have anymore questions. Thanks!

**Comment by seladore** [comment]
oh really, that's so interesting
thanks for making the changes

**Pull request merged**
